# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Goniometer_Alpha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtMultimedia import *
from PyQt5.QtMultimediaWidgets import *
import os
import sys
import time


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):

        super().__init__()

        # getting available camera
        self.available_cameras = QCameraInfo.availableCameras()

        # creating a QCameraViewfinder object
        self.viewfinder = QCameraViewfinder()

        # showing this viewfinder
        self.viewfinder.show()

        # setting up main window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 565)
        MainWindow.setBaseSize(QtCore.QSize(100, 100))

        # setting up central widget
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # setting up layout and subwidgets
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fps_dialogue = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fps_dialogue.setObjectName("fps_dialogue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fps_dialogue)
        self.Start_Stop_Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Start_Stop_Label.setFont(font)
        self.Start_Stop_Label.setObjectName("Start_Stop_Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Start_Stop_Label)
        self.Start_Stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Stop_Button.setObjectName("Start_Stop_Button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Start_Stop_Button)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.recording_indicator = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recording_indicator.sizePolicy().hasHeightForWidth())
        self.recording_indicator.setSizePolicy(sizePolicy)
        self.recording_indicator.setMinimumSize(QtCore.QSize(16, 16))
        self.recording_indicator.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.recording_indicator.setFont(font)
        self.recording_indicator.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recording_indicator.setText("")
        self.recording_indicator.setPixmap(QtGui.QPixmap("graphics/red_indicator.png"))
        self.recording_indicator.setScaledContents(True)
        self.recording_indicator.setObjectName("recording_indicator")
        self.horizontalLayout.addWidget(self.recording_indicator)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.horizontalLayout_2.addLayout(self.formLayout)

        # video widget setup
        self.Video = self.viewfinder
        self.select_camera(0)

        # arguments for the video widget
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.Video.sizePolicy().hasHeightForWidth())
        self.Video.setSizePolicy(sizePolicy)
        self.Video.setObjectName("Video")
        self.horizontalLayout_2.addWidget(self.Video)

        # MainWindow setup, I think?
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionChange_Save_Directory = QtWidgets.QAction(MainWindow)
        self.actionChange_Save_Directory.setObjectName("actionChange_Save_Directory")
        self.menuFile.addAction(self.actionChange_Save_Directory)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # method to select camera
    def select_camera(self, i):
        # getting the selected camera
        self.camera = QCamera(self.available_cameras[i])

        # setting view finder to the camera
        self.camera.setViewfinder(self.viewfinder)

        # setting capture mode to the camera
        self.camera.setCaptureMode(QCamera.CaptureStillImage)

        # if any error occur show the alert
        self.camera.error.connect(lambda: self.alert(self.camera.errorString()))

        # start the camera
        self.camera.start()

        # creating a QCameraImageCapture object
        self.capture = QCameraImageCapture(self.camera)

        # showing alert if error occur
        self.capture.error.connect(lambda error_msg, error,
                                              msg: self.alert(msg))

        # when image captured showing message
        self.capture.imageCaptured.connect(lambda d,
                                                      i: self.status.showMessage("Image captured : "
                                                                                 + str(self.save_seq)))

        # getting current camera name
        self.current_camera_name = self.available_cameras[i].description()

        # initial save sequence
        self.save_seq = 0

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Video Name:"))
        self.label_2.setText(_translate("MainWindow", "Frame Rate (fps):"))
        self.Start_Stop_Label.setText(_translate("MainWindow", "Start/Stop:"))
        self.Start_Stop_Button.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "Recording Indicator"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionChange_Save_Directory.setText(_translate("MainWindow", "Change Save Directory"))
        self.actionChange_Save_Directory.setWhatsThis(_translate("MainWindow", "Ctrl + S"))
        self.actionChange_Save_Directory.setShortcut(_translate("MainWindow", "Ctrl+S"))
#import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
